### ISSUE TITLE
The first newline is deleted in code tags

### ISSUE THREAD

**Issue by ScoreUnder** [ctrlcctrlv/infinity#490] opened 2015-05-01 06:50 UTC
```
[code]#!/bin/sh
echo this is some code[/code]
```
![Result](https://a.pomf.se/uzjgcu.png)

**Comment by 8n-tech** [comment] 2015-05-01 09:38
Looking into it.

**Comment by ScoreUnder** [comment] 2015-05-07 10:13
This is "fixed" on 8ch but it looks like a reversion of the change that broke it. I'll leave this open because I don't know if it will be reimplemented.

**Comment by 8n-tech** [comment] 2015-05-07 11:54
It is not undoing a feature. All I changed was how large block elements 
handle line breaking.

**Comment by ScoreUnder** [comment] 2015-05-07 21:20
I don't mean this commit, but the current code running on 8ch seems to have had the change reverted. See this screenshot:

![Screenshot](https://i.imgur.com/Ls3qqrT.png)

**Comment by 8n-tech** [comment] 2015-05-08 07:23
That's a separate issue. If you put a line break after the first [code] tag it interprets that literally.

**Comment by ctrlcctrlv** [comment] 2015-05-08 09:42
Closing, feature not a bug.

**Closed by ctrlcctrlv** 2015-05-08 09:42 UTC
